---
title: "Hei!"
---

This website features all `R` tutorials for the BST290 *Kvantitativ forskningsmetode* course. Simply use the menu on the side to navigate to and between the different tutorials and use the search field (top right) to find tutorials with specific contents.

::: {.callout-important}

To make reading the tutorials easier and quicker, **download them as PDFs and print them out**. There are download buttons at the beginning of each tutorial (under the table of contents on the right side). You *can* of course read all the material "on screen" if you really want to, but that is not recommended. Ideally, you read each of the tutorials first on paper and you use this website mainly to quickly look things up later.

:::

::: {.callout-note title = "To cite the tutorials, please use:"}

> Knotz, Carlo. 2026. "[Title of tutorial]" *R Tutorials for BST290* [link_to_tutorial](https://cknotz.github.io/bst290_tutorials_site/)

:::

::: {.callout-tip}

Some students wrote their own short tutorials on how to solve common problems that students who are just learning how to work with `R` often run into (e.g., prompt engineering with *ChatGPT* and additional data visualization tricks). You might find these very helpful. You can find these tutorials on [kodehjornet.github.io](https://kodehjornet.github.io/){.external target="_blank"}.

:::


If you have questions, notice something that is wrong or is not shown properly, please send an email to [carlo.knotz@uis.no](mailto:carlo.knotz@uis.no).

That's it. Lykke til!